with open("input.txt","r") as f:
    x=f.readline()
    lista1=list(x)
    print(lista1)
    lista2=sorted(lista1)
    print(lista2)
    lista3=list(x)
    lista3.sort(reverse=True)
    print(lista3)
    print(len(x))
    print(min(x))
    print(max(x))
    lista4=list(x)
    lista4.extend([111])
    print(lista4)
    lista5=list(x)
    lista5.insert(2,222)
    print(lista5)
